---
UncommunicativeParameterName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
TooManyMethods:
  max_methods: 10
  exclude:
  - Morpher::Printer # 16 methods
  enabled: true
  max_instance_variables: 2
UncommunicativeMethodName:
  accept: ['s']
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
LongParameterList:
  max_params: 3  # TODO: decrease max_params to 2
  exclude: []
  enabled: true
  overrides: {}
FeatureEnvy:
  exclude:
  # False positives:
  - Morpher::Printer::Mixin::InstanceMethods#description
  - Morpher::Evaluator::Transformer::Domain::AttributeHash::Dump#call
  - Morpher::Evaluator::Transformer::Domain::AttributeAccessors::Load#call
  - Morpher::Evaluator::Transformer::Domain::InstanceVariables::Load#call
  - Morpher::Evaluator::Transformer::Domain::InstanceVariables::Dump#call
  enabled: true
ClassVariable:
  exclude: []
  enabled: true
BooleanParameter:
  exclude: []
  enabled: true
IrresponsibleModule:
  exclude:
  # False positives
  - Morpher::Compiler
  - Morpher::Compiler::Preprocessor
  - Morpher::Compiler::Evaluator
  enabled: true
UncommunicativeModuleName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
NestedIterators:
  ignore_iterators: []
  exclude: []
  enabled: true
  max_allowed_nesting: 2
TooManyStatements:
  max_statements: 7  # TODO: decrease max_statements to 5 or less
  exclude:
    - Morpher::Compiler::Emitter#self.children
  enabled: true
DuplicateMethodCall:
  allow_calls: []
  exclude: []
  enabled: false # TOOD enable
  max_calls: 1
UtilityFunction:
  max_helper_calls: 1
  exclude:
  - Morpher::Evaluator::Predicate::Contradiction#inverse
  - Morpher::Evaluator::Predicate::Tautology#inverse
  - Morpher::Evaluator::Transformer::Coerce::ParseIso8601DateTime#invoke
  - Morpher::Evaluator::Transformer::Domain::AttributeHash::Dump#call
  enabled: true
Attribute:
  exclude: []
  enabled: false
UncommunicativeVariableName:
  accept: ['_']
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
RepeatedConditional:
  exclude: []
  enabled: true
  max_ifs: 2
DataClump:
  exclude: []
  enabled: true
  max_copies: 1
  min_clump_size: 3
ControlParameter:
  exclude: []
  enabled: true
LongYieldList:
  max_params: 1
  exclude: []
  enabled: true
NilCheck:
  exclude: []
