---
engines:
  brakeman:
    enabled: true
    checks:
      # disable 'Parameter value used in file name', 
      # I (Zhewei) cannot find a good way to handle this problem right now.
      file_access:
        enabled: false 
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
exclude_paths:
- 'bin/**/*'
- 'config/**/*'
- 'db/**/*'
- 'lib/**/*'
- 'public/**/*'
- 'vendor/**/*'
