source 'https://rubygems.org'

gem 'rails', '7.0.4.1'

## Gems in Alphabetical Order
gem 'actionpack', '7.0.4.1'
gem 'activerecord', '7.0.4.1'
gem 'activerecord-session_store', '2.0.0'
gem 'activesupport', '7.0.4.1'
gem 'airbrake', '5.2.0'
gem 'authlogic', '6.4.2'
gem 'awesome_nested_set', '3.5.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.47'
gem 'bullet', '~> 5.7.6'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-db-tasks', require: false
# https://www.phusionpassenger.com/library/deploy/apache/automating_app_updates/ruby/
gem 'capistrano-passenger'
gem 'capistrano-rails'
gem 'capistrano-rvm'
gem 'chartjs-ror'
gem 'coffee-rails'
gem 'coveralls', require: false
gem 'danger', git: 'https://github.com/Winbobob/danger.git', ref: '1ccfed23f809a1e5c46e2533cfd7a3138f6cd821', require: false
gem 'delayed_job_active_record', '4.1.7'
gem 'dotenv-rails', :require => 'dotenv/rails-now'
gem 'dynamic_form'
gem 'edavis10-ruby-web-search'
gem 'engtagger'
gem 'fastercsv'
gem 'font-awesome-rails'
gem 'foreman'
gem 'gchartrb', require: 'google_chart'
gem 'gdata', require: false
gem 'haml-rails'
gem 'jquery-colorbox-rails'
gem 'jquery-datetimepicker-rails'
gem 'jquery-rails'
gem 'jquery-tablesorter'
gem 'jquery-ui-sass-rails'
gem 'json'
gem 'lingua'
gem 'mimemagic', git: 'https://github.com/mimemagicrb/mimemagic.git', ref: '01f92d86d15d85cfd0f20dabd025dcbd36a8a60f'
gem 'momentjs-rails', '>= 2.9.0'
gem 'mysql2', '0.4.10'
gem 'nokogiri', '1.10.10'
gem 'omniauth-google-oauth2'
gem 'open-uri-cached'
gem 'paper_trail'
gem 'pragmatic_segmenter'
gem 'rails4-autocomplete'
gem 'rake'
gem 'rb-readline'
gem 'react-rails'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'RedCloth'
gem 'redis-namespace'
gem 'redis-rails', '5.0.2'
gem 'rest-client'
gem 'rgl', require: 'rgl/adjacency'
gem 'rjb'
gem 'rubyzip'
gem 'rwordnet'
gem 'sass-rails', '6.0.0'
gem 'scrypt', '3.0.6'
gem 'seer'
gem 'shoulda-matchers'
gem 'sidekiq'
gem 'sprockets'
gem 'superfish-rails'
gem 'therubyracer'
gem 'thin'
gem 'timecop'
gem 'tinymce-rails'
gem 'uglifier'
gem 'will_paginate'
gem 'zip-zip'
gem 'railties', '7.0.4.1'
gem 'redis-actionpack', '5.3.0'

group :development do
  gem 'daemons'
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-remote'
  gem 'rubocop'
end

group :test do
  gem 'database_cleaner'
  gem "factory_bot_rails", '4.8.2'
  gem 'geckodriver-helper', '~> 0.0.3'
  gem 'gherkin'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'launchy'
  gem 'rspec-rails', '6.0.1'
  gem 'rails-controller-testing'
  gem 'puma'
  gem 'shoulda'
end

group :development, :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
end
