branch-defaults:
  master:
    environment: rails-beanstalk-env
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 running Ruby 2.2 (Passenger
    Standalone)
  default_region: us-east-1
  profile: eb-cli
  sc: git
