:chart:
  :type: 'scatter'
  :zoomType: 'xy'
:title:
  :text: 'Height Versus Weight of 507 Individuals by Gender'
:subtitle:
  :text: 'Source: Heinz  2003'
:xAxis:
  :title:
    :enabled: true
    :text: 'Height (cm)'
  :startOnTick: true
  :endOnTick: true
  :showLastLabel: true
:yAxis:
  :title:
    :text: 'Weight (kg)'
:legend:
  :layout: 'vertical'
  :align: 'left'
  :verticalAlign: 'top'
  :x: 100
  :y: 70
  :floating: true
  :backgroundColor: '#FFFFFF'
  :borderWidth: 1
:plotOptions:
  :scatter:
    :marker:
      :radius: 5
      :states:
        :hover:
          :enabled: true
          :lineColor: 'rgb(100,100,100)'
    :states:
      :hover:
        :marker:
          :enabled: false
    :tooltip:
      :headerFormat => '<b>{series.name}</b><br>'
      :pointFormat => '{point.x} cm, {point.y} kg'
    :series: [
      {
        name: 'Female',
        color: 'rgba(223, 83, 83, .5)',
        data: [[161.2, 51.6], [167.5, 59.0], [159.5, 49.2], [157.0, 63.0], [155.8, 53.6],
              [169.5, 67.3], [160.0, 75.5], [172.7, 68.2], [162.6, 61.4], [157.5, 76.8],
              [176.5, 71.8], [164.4, 55.5], [160.7, 48.6], [174.0, 66.4], [163.8, 67.3]]

      }, {
        name: 'Male',
        color: 'rgba(119, 152, 191, .5)',
        data: [[174.0, 65.6], [175.3, 71.8], [193.5, 80.7], [186.5, 72.6], [187.2, 78.8],
              [170.2, 62.3], [177.8, 82.7], [179.1, 79.1], [190.5, 98.2], [177.8, 84.1],
              [180.3, 83.2], [180.3, 83.2]]
      }]