# E2111 Github Metrics -- Used to list Expertiza Organization Members whose commits should not be credited to student projects.
# Add account Expertiza developing team's github account into this file
# For example, setting:
# COLLABORATORS: 'Expertiza Developer'
# extend this list with comma separated github ids
# the list is available as ENV["COLLABORATORS"]
development:
  COLLABORATORS: 'efg@ncsu.edu,sgpai2@ncsu.edu,saurabh.shingte@gmail.com'

test:
  COLLABORATORS: 'efg@ncsu.edu,sgpai2@ncsu.edu,saurabh.shingte@gmail.com'

production:
  COLLABORATORS: 'efg@ncsu.edu,sgpai2@ncsu.edu,saurabh.shingte@gmail.com'
