# Rename this file to local_env.yml
# Add account Expertiza developing team's github account into this file
# For example, setting:
# BLACKLIST_AUTHOR: 'Expertiza Developer'
# extend this list wiht comma separated github ids
# the list is available as ENV["BLACKLIST_AUTHOR"]
development:
  COLLABORATORS: 'efg@ncsu.edu,sgpai2@ncsu.edu,saurabh.shingte@gmail.com'

test:
  COLLABORATORS: 'efg@ncsu.edu,sgpai2@ncsu.edu,saurabh.shingte@gmail.com'

production:
  COLLABORATORS: 'efg@ncsu.edu,sgpai2@ncsu.edu,saurabh.shingte@gmail.com'
