development:
  offensive: 'lame', 'stupid'
  problem: 'http://peerlogic.csc.ncsu.edu/reputation/calculations/reputation_algorithms'
  suggestive: 'http://peerlogic.csc.ncsu.edu/sum/v1.0/summary/8/lsa'

test:
  offensive: 'http://peerlogic.csc.ncsu.edu/metareview/metareviewgenerator/'
  problem: 'http://peerlogic.csc.ncsu.edu/reputation/calculations/reputation_algorithms'
  suggestive: 'http://peerlogic.csc.ncsu.edu/sum/v1.0/summary/8/lsa'

production:
  offensive: 'http://peerlogic.csc.ncsu.edu/metareview/metareviewgenerator/'
  problem: 'http://peerlogic.csc.ncsu.edu/reputation/calculations/reputation_algorithms'
  suggestive: 'http://peerlogic.csc.ncsu.edu/sum/v1.0/summary/8/lsa'