development:
  offensive: ["lame","stupid","dumb","idiot","horrendous","horrible","non-sense","crap","piss","pissed","bullshit","bloody","hell","stupidity"]
  problem: ["wrong","error","problem","issue","problems","errors","issues","problematic","fix","obstacle","dispute","not","none","didn't","cannot","can't","couldn't","shouldn't"]
  suggestive: ["should","recommend","suggest","advise","try","can","maybe","could","may","would","should've","could've","would've","plan"]

test:
  offensive: ["lame","stupid","dumb","idiot","horrendous","horrible","non-sense","crap","piss","pissed","bullshit","bloody","hell","stupidity"]
  problem: ["wrong","error","problem","issue","problems","errors","issues","problematic","fix","obstacle","dispute","not","none","didn't","cannot","can't","couldn't","shouldn't"]
  suggestive: ["should","recommend","suggest","advise","try","can","maybe","could","may","would","should've","could've","would've","plan"]

production:
  offensive: ["lame","stupid","dumb","idiot","horrendous","horrible","non-sense","crap","piss","pissed","bullshit","bloody","hell","stupidity"]
  problem: ["wrong","error","problem","issue","problems","errors","issues","problematic","fix","obstacle","dispute","not","none","didn't","cannot","can't","couldn't","shouldn't"]
  suggestive: ["should","recommend","suggest","advise","try","can","maybe","could","may","would","should've","could've","would've","plan"]