export const PROFILE_FAILED = 'PROFILE_LOADING';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_INSTITUTIONS = 'ADD_INSTITUTIONS';

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
