# This is a basic workflow that uses Capistrano to deploy Expertiza on Production, Test, and Development servers
name: Deploy with Capistrano

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'test'
        type: choice
        options:
          - production
          - development
          - test

jobs:
    if: inputs.environment == 'production'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java Path
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - uses: miloserdow/capistrano-deploy@master
        with:
          target: production # Defines the environment for the deployment
          enc_rsa_key_val: ${{ secrets.ENCRYPTED_PRIVATE_KEY_PROD }}
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
      

# development and test jobs are identical - with different target environment and server keys
  development:
    if: inputs.environment == 'development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV_B64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 152.7.179.114 >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - name: Deploy with Capistrano
        run: bundle exec cap development deploy

  test:
    if: inputs.environment == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - uses: miloserdow/capistrano-deploy@master
        with:
          target: staging
          enc_rsa_key_val: ${{ secrets.ENCRYPTED_PRIVATE_KEY_STAGING }}
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
